services:
  - type: web
    name: fastapi-tutorial
    runtime: python
    plan: free # Free tier: 512 MB RAM, spins down after 15 min inactivity
    buildCommand: "pip install uv && uv sync"
    startCommand: "uv run uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: DATABASE_URL
        fromDatabase:
          name: fastapi-db
          property: connectionString